In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt
import os
import math
import time
import datetime

In [2]:
path='D:\\桌面\\處理好的csv_ver_20200915\\'

day_list = os.listdir(path)
day_list

['json_Combine_txt_ToCSV_0804.csv',
 'json_Combine_txt_ToCSV_0805.csv',
 'json_Combine_txt_ToCSV_0806.csv',
 'json_Combine_txt_ToCSV_0807.csv',
 'json_Combine_txt_ToCSV_0808.csv',
 'json_Combine_txt_ToCSV_0809.csv',
 'json_Combine_txt_ToCSV_0810.csv',
 'json_Combine_txt_ToCSV_0811.csv',
 'json_Combine_txt_ToCSV_0812.csv',
 'json_Combine_txt_ToCSV_0813.csv']

In [4]:
df_After_combine = pd.read_csv(path+day_list[0])
df_After_combine = df_After_combine.drop(['Unnamed: 0'],axis=1)
df_After_combine

,Timestamp,Z1,Z1_max,Z1_min,machine_Status,Temperature,Current
0,2020-08-04 03:06:00,-0.095732,0.190430,-0.439453,0,30.2,0
1,2020-08-04 03:06:01,-0.096666,0.328369,-0.400391,0,30.2,0
2,2020-08-04 03:06:02,-0.093258,0.086670,-0.389404,0,30.2,0
3,2020-08-04 03:06:03,-0.095028,0.192871,-0.327148,0,30.2,0
4,2020-08-04 03:06:04,-0.093034,0.185547,-0.495605,0,30.2,0
...,...,...,...,...,...,...,...
75115,2020-08-04 23:59:55,0.171827,0.411377,-0.079346,0,32.1,0
75116,2020-08-04 23:59:56,0.171558,0.526123,-0.283203,0,32.1,0
75117,2020-08-04 23:59:57,0.169330,0.432129,-0.106201,0,32.1,0
75118,2020-08-04 23:59:58,0.169414,0.526123,-0.046387,0,32.1,0
75119,2020-08-04 23:59:59,0.169897,0.434570,-0.037842,0,32.1,0

In [5]:
df_produce = pd.read_csv('D:\\桌面\\製程資料.csv')
df_produce

,Product,Production_tonnage(T),machine_open(H),machine_close(H),Active_time(H),Utilization_capacity(T/H),Hole_size,Cutters,Clean_mould
0,0,56.1,2020/8/3 09:30,2020/8/3 19:00,9.50,5.91,0,2,1
1,1,61.6,2020/8/4 09:10,2020/8/4 19:30,10.33,5.96,0,2,1
2,2,20.0,2020/8/5 08:30,2020/8/5 12:20,3.83,5.20,0,2,0
3,3,31.9,2020/8/5 13:20,2020/8/5 19:00,5.67,5.63,0,2,1
4,4,15.4,2020/8/6 09:35,2020/8/6 12:15,2.67,5.77,1,2,0
5,5,13.2,2020/8/6 13:15,2020/8/6 15:30,2.25,5.78,1,2,1
6,5,41.8,2020/8/7 08:30,2020/8/7 15:30,7.00,5.97,1,2,1
7,6,10.0,2020/8/10 09:30,2020/8/10 10:40,8.17,1.22,1,2,1
8,6,10.0,2020/8/10 11:40,2020/8/10 12:20,8.17,1.22,1,2,1
9,6,10.0,2020/8/10 13:20,2020/8/10 15:20,8.17,1.22,1,2,1
10,6,10.0,2020/8/10 15:50,2020/8/10 17:40,8.17,1.22,1,2,1
11,6,10.0,2020/8/10 18:40,2020/8/10 21:00,8.17,1.22,1,2,1
12,7,35.0,2020/8/11 09:40,2020/8/11 15:30,5.83,6.00,0,2,1
13,3,39.6,2020/8/12 08:40,2020/8/12 15:30,6.83,5.80,0,2,1

In [66]:
def find_Index_wrong_position(correct_Time_strat,correct_Time_end,dataframe):
    
    def_shape = dataframe.shape
#     time_start = 0
#     time_end = 0
    time_list = []
    for def_line in range(def_shape[0]):

        
        tmp_Time_format = pd.to_datetime(str(dataframe.iloc[def_line,0])).strftime("%Y-%m-%d %H:%M:%S")

        if tmp_Time_format == correct_Time_strat:
            time_start = def_line
            time_list.append(def_line)
        elif tmp_Time_format == correct_Time_end:
            time_end = def_line
            time_list.append(def_line+1)
            return time_list
            
#         if error_Time == time_Format_e and correct_Time == time_Format_c:
#             print(dataframe.loc[0:def_line+1])
#             return def_line
#         else:
#             print('又有bug啦RRRR')

In [96]:
df1 = pd.to_datetime(df_produce.iloc[:,2],format="%Y/%m/%d %H:%M")
df1[0].strftime("%m%d")
df1

0    2020-08-03 09:30:00
1    2020-08-04 09:10:00
2    2020-08-05 08:30:00
3    2020-08-05 13:20:00
4    2020-08-06 09:35:00
5    2020-08-06 13:15:00
6    2020-08-07 08:30:00
7    2020-08-10 09:30:00
8    2020-08-10 11:40:00
9    2020-08-10 13:20:00
10   2020-08-10 15:50:00
11   2020-08-10 18:40:00
12   2020-08-11 09:40:00
13   2020-08-12 08:40:00
Name: machine_open(H), dtype: datetime64[ns]

In [9]:
for file_list in day_list:    
    split_filename = file_list.split('_')
    splitfile_name = split_filename[4].split('.')
    print(splitfile_name[0])

D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0804.csv
0804
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0805.csv
0805
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0806.csv
0806
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0807.csv
0807
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0808.csv
0808
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0809.csv
0809
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0810.csv
0810
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0811.csv
0811
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0812.csv
0812
D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0813.csv
0813

In [109]:
df_Produce_shape = df_produce.shape
df_strat = pd.to_datetime(df_produce.iloc[:,2],format="%Y/%m/%d %H:%M")
df_end = pd.to_datetime(df_produce.iloc[:,3],format="%Y/%m/%d %H:%M")

tmp_List_time_count = []

for time_count in range(df_Produce_shape[0]):
    try:
        tmp_Df = pd.read_csv(path+'json_Combine_txt_ToCSV_'+Month_Day+'.csv')
        Month_Day_list = df1[time_count].strftime("%m%d")
        tmp_List_time_count.append(Month_Day_list)
    except Exception as e:
        print('Error_1: ',e)
        
tmp_List_time_count_unique = np.unique(tmp_List_time_count)
# tmp_List_time_count_unique
# tmp_List_time_count.index(tmp_List_time_count_unique[7])
# tmp_List_time_count.count(tmp_List_time_count_unique[5])
for time_produce in tmp_List_time_count_unique:
    try:
        df_csv_ver1 = pd.read_csv(path+'json_Combine_txt_ToCSV_'+Month_Day+'.csv')
        index_time = tmp_List_time_count.index(time_produce)
        count_time = tmp_List_time_count.count(time_produce)
        for many_time in range(int(count_time)):
            index_time
        
    except Exception as e:
# for time_produce in range(df_Produce_shape[0]):
#     try:
#         Month_Day = df1[time_produce].strftime("%m%d")
#         df_csv_ver1 = pd.read_csv(path+'json_Combine_txt_ToCSV_'+Month_Day+'.csv')
#         df_csv_ver1['work_stat'] = ''
#         df_csv_ver1.fillna(value=0, inplace=True)
#         start_time = str(df_strat[time_produce])
#         end_time = str(df_end[time_produce])
#         print(start_time,end_time)
#         position_list = find_Index_wrong_position(start_time,end_time,df_csv_ver1)
#         print('position:',position_list[0],position_list[1])

#         df_csv_ver1.iloc[position_list[0]:position_list[1],22] = df_produce.iloc[time_produce,0]
#         df_csv_ver1.iloc[position_list[0]:position_list[1],23] = df_produce.iloc[time_produce,1]
#         df_csv_ver1.iloc[position_list[0]:position_list[1],24] = df_produce.iloc[time_produce,4]
#         df_csv_ver1.iloc[position_list[0]:position_list[1],25] = df_produce.iloc[time_produce,5]
#         df_csv_ver1.iloc[position_list[0]:position_list[1],26] = df_produce.iloc[time_produce,6]
#         df_csv_ver1.iloc[position_list[0]:position_list[1],27] = df_produce.iloc[time_produce,7]
#         df_csv_ver1.iloc[position_list[0]:position_list[1],28] = df_produce.iloc[time_produce,8]
#         df_csv_ver1.iloc[position_list[0]:position_list[1],29] = 1
# #         df_csv_ver1.fillna(value=0, inplace=True)
# #         print(df_csv_ver1)
#         df_csv_ver1.to_csv(path+'json_Combine_txt_ToCSV_'+Month_Day+'_Ver4.csv',index=False)
        
#     except Exception as e:
#         print('Error: ',e)

5

In [132]:
df_Produce_shape = df_produce.shape
df_strat = pd.to_datetime(df_produce.iloc[:,2],format="%Y/%m/%d %H:%M")
df_end = pd.to_datetime(df_produce.iloc[:,3],format="%Y/%m/%d %H:%M")

for time_produce in range(df_Produce_shape[0]):
    try:
        Month_Day = df1[time_produce].strftime("%m%d")
        df_csv_ver1 = pd.read_csv(path+'json_Combine_txt_ToCSV_'+Month_Day+'.csv')
        
        check_columns = df_csv_ver1.columns
#         print(check_columns[-1])
        if check_columns[-1] != 'work_stat':
            df_csv_ver1['work_stat'] = 0
            
        
        start_time = str(df_strat[time_produce])
        end_time = str(df_end[time_produce])
        print(start_time,end_time)
        position_list = find_Index_wrong_position(start_time,end_time,df_csv_ver1)
        print('position:',position_list[0],position_list[1])

        df_csv_ver1.iloc[position_list[0]:position_list[1],22] = df_produce.iloc[time_produce,0]
        df_csv_ver1.iloc[position_list[0]:position_list[1],23] = df_produce.iloc[time_produce,1]
        df_csv_ver1.iloc[position_list[0]:position_list[1],24] = df_produce.iloc[time_produce,4]
        df_csv_ver1.iloc[position_list[0]:position_list[1],25] = df_produce.iloc[time_produce,5]
        df_csv_ver1.iloc[position_list[0]:position_list[1],26] = df_produce.iloc[time_produce,6]
        df_csv_ver1.iloc[position_list[0]:position_list[1],27] = df_produce.iloc[time_produce,7]
        df_csv_ver1.iloc[position_list[1]-1,28] = df_produce.iloc[time_produce,8]
        df_csv_ver1.iloc[position_list[0]:position_list[1],29] = 1
        df_csv_ver1.fillna(value=0, inplace=True)
#         print(df_csv_ver1)
        df_csv_ver1.to_csv(path+'json_Combine_txt_ToCSV_'+Month_Day+'.csv',index=False)
        
    except Exception as e:
        print('Error: ',e)

Error:  [Errno 2] File D:\桌面\處理好的csv_ver_20200915\json_Combine_txt_ToCSV_0803.csv does not exist: 'D:\\桌面\\處理好的csv_ver_20200915\\json_Combine_txt_ToCSV_0803.csv'
2020-08-04 09:10:00 2020-08-04 19:30:00
position: 364 983
2020-08-05 08:30:00 2020-08-05 12:20:00
position: 510 741
2020-08-05 13:20:00 2020-08-05 19:00:00
position: 800 1141
2020-08-06 09:35:00 2020-08-06 12:15:00
position: 575 736
2020-08-06 13:15:00 2020-08-06 15:30:00
position: 795 931
2020-08-07 08:30:00 2020-08-07 15:30:00
position: 510 931
2020-08-10 09:30:00 2020-08-10 10:40:00
position: 570 641
2020-08-10 11:40:00 2020-08-10 12:20:00
position: 700 741
2020-08-10 13:20:00 2020-08-10 15:20:00
position: 800 921
2020-08-10 15:50:00 2020-08-10 17:40:00
position: 950 1061
2020-08-10 18:40:00 2020-08-10 21:00:00
position: 1120 1261
2020-08-11 09:40:00 2020-08-11 15:30:00
position: 580 931
2020-08-12 08:40:00 2020-08-12 15:30:00
position: 520 931

In [129]:
a = df_csv_ver1.columns
a[-1]

'work_stat'

In [83]:
print(df.iloc[0,2])
print(type(df.iloc[0,2]))
time_test = datetime.datetime.strptime(df.iloc[0,2],"%Y/%m/%d %H:%M").strftime("%Y%m%d%H")
time_test

NameError: name 'df' is not defined

In [ ]:
produceData_Path = 'D:\\桌面\\製程資料.csv'
df_Csv_produce = pd.read_csv(produceData_Path)

In [130]:
df_csv_ver1

,Timestamp,Z1_mean,Z1_max,Z1_min,Z1_std,Z1_skew,Z1_kurtosis,Z1_peakTopeak,Z1_RMS,Z1_crestFactor,...,Current_avg,Current_max,Product,Production,Active_time(H),Utilization_capacity(T/H),Hole_size,Cutters,Clean_mould,work_stat
0,2020-08-12 00:00:00,0.170890,0.611572,-0.285645,0.056708,0.047768,12.936974,0.897217,0.179988,3.397849,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-08-12 00:01:00,0.170915,0.581055,-0.295410,0.055922,-0.047930,13.171995,0.876465,0.179889,3.230072,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-08-12 00:02:00,0.169643,0.581055,-0.308838,0.057190,-0.126738,11.688039,0.889893,0.179515,3.236812,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-08-12 00:03:00,0.171002,0.601807,-0.272217,0.056165,0.155923,12.090850,0.874023,0.180239,3.338931,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-08-12 00:04:00,0.170895,0.588379,-0.288086,0.055975,-0.055336,13.032367,0.876465,0.180258,3.264090,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,2020-08-12 23:55:00,0.171022,0.599365,-0.301514,0.058136,0.014541,12.804110,0.900879,0.180983,3.311719,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1436,2020-08-12 23:56:00,0.170975,0.588379,-0.285645,0.056785,-0.066051,11.956941,0.874023,0.179876,3.271028,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1437,2020-08-12 23:57:00,0.170835,0.578613,-0.295410,0.055086,0.145663,12.668288,0.874023,0.180104,3.212656,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1438,2020-08-12 23:58:00,0.170811,0.588379,-0.306396,0.056707,-0.282166,13.856104,0.894775,0.179654,3.275062,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1439,2020-08-12 23:59:00,0.171069,0.606689,-0.280762,0.056340,0.241979,11.986803,0.887451,0.180916,3.353439,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0